### ISSUE TITLE
error when trying to install 

### ISSUE THREAD

**Issue by elba7r** [ESS-LLP/erpnext#15]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/his/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/his/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/his/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/his/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/his/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/his/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/his/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/his/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/his/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/his/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/his/apps/frappe/frappe/commands/site.py", line 152, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/frappe/his/apps/frappe/frappe/installer.py", line 133, in install_app
    sync_for(name, force=True, sync_everything=True, verbose=verbose, reset_permissions=True)
  File "/home/frappe/his/apps/frappe/frappe/model/sync.py", line 44, in sync_for
    import_file_by_path(doc_path, force=force, reset_permissions=reset_permissions)
  File "/home/frappe/his/apps/frappe/frappe/modules/import_file.py", line 57, in import_file_by_path
    reset_permissions=reset_permissions)
  File "/home/frappe/his/apps/frappe/frappe/modules/import_file.py", line 125, in import_doc
    doc.insert()
  File "/home/frappe/his/apps/frappe/frappe/model/document.py", line 212, in insert
    self.run_post_save_methods()
  File "/home/frappe/his/apps/frappe/frappe/model/document.py", line 770, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/his/apps/frappe/frappe/model/document.py", line 651, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/his/apps/frappe/frappe/model/document.py", line 860, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/his/apps/frappe/frappe/model/document.py", line 843, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/his/apps/frappe/frappe/model/document.py", line 645, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/his/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 197, in on_update
    self.run_module_method("on_doctype_update")
  File "/home/frappe/his/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 206, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "/home/frappe/his/apps/frappe/frappe/modules/utils.py", line 173, in load_doctype_module
    raise ImportError, 'Module import failed for {0} ({1})'.format(doctype, module_name)
ImportError: Module import failed for Purchase Taxes and Charges Template (erpnext.accounts.doctype.purchase_taxes_and_charges_template.purchase_taxes_and_charges_template)

**Comment by rkurungadam** [comment]
Please try installing from https://github.com/frappe/erpnext
